modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="project"
version="1.0.0"
displayName="Project"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Pedro, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.project]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.project]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration